[build]
publish = "site"
command = """
python setup.py install &&
pip3 install --no-cache-dir -r requirements.txt &&
mkdocs build &&
mkdocs build -f mkdocs-4.2.yml &&
mkdocs build -f mkdocs-4.0.yml &&
mkdocs build -f mkdocs-3.6.yml &&
mkdocs build -f mkdocs-2.18.yml
"""
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains"
