{{- if .Values.apiFirewall.ingress.enabled -}}
{{- if not (len .Values.apiFirewall.ingress.hosts) -}}
{{- fail "You must define .apiFirewall.ingress.hosts for using Ingress objects" -}}
{{- end -}}
apiVersion: {{ template "ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ template "api-firewall.fullname" . }}
  labels:
    app: {{ template "api-firewall.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: api-firewall
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  {{- if .Values.apiFirewall.ingress.annotations }}
  annotations: {{ .Values.apiFirewall.ingress.annotations | toYaml | trimSuffix "\n" | nindent 4 }}
  {{- end }}
spec:
  {{ if .Values.apiFirewall.ingress.ingressClass -}}
  ingressClassName: {{ .Values.apiFirewall.ingress.ingressClass }}
  {{ end -}}
  {{ if .Values.apiFirewall.ingress.hosts -}}
  rules:
  {{ range .Values.apiFirewall.ingress.hosts -}}
  - host: {{ . }}
    http:
      paths:
      - path: {{ $.Values.apiFirewall.ingress.path }}
        backend:
          {{- if $.Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
          service:
            name: {{ template "api-firewall.fullname" $ }}
            port:
              number: {{ $.Values.apiFirewall.service.port }}
          {{- else }}
          serviceName: {{ template "api-firewall.fullname" $ }}
          servicePort: {{ $.Values.apiFirewall.service.port }}
          {{- end }}
  {{ end -}}
  {{ end -}}
  {{ if .Values.apiFirewall.ingress.tls -}}
  tls: {{ toYaml .Values.apiFirewall.ingress.tls | trimSuffix "\n" | nindent 2 }}
  {{ end -}}
{{- end }}
