{{- if .Values.apiFirewall.podSecurityPolicy.enabled}}
apiVersion: {{ template "podSecurityPolicy.apiVersion" . }}
kind: PodSecurityPolicy
metadata:
  name: {{ template "api-firewall.fullname" . }}
  labels:
    app: {{ template "api-firewall.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: api-firewall
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  {{ if len .Values.apiFirewall.podSecurityPolicy.allowedCapabilities -}}
  allowedCapabilities: {{ .Values.apiFirewall.podSecurityPolicy.allowedCapabilities | toYaml | trimSuffix "\n" | nindent 2 }}
  {{ end -}}
  privileged: {{ .Values.apiFirewall.podSecurityPolicy.privileged }}
  allowPrivilegeEscalation: {{ .Values.apiFirewall.podSecurityPolicy.allowPrivilegeEscalation }}
  {{ if len .Values.apiFirewall.podSecurityPolicy.volumes -}}
  volumes: {{ .Values.apiFirewall.podSecurityPolicy.volumes | toYaml | trimSuffix "\n" | nindent 2 }}
  {{ end -}}
  hostNetwork: {{ .Values.apiFirewall.podSecurityPolicy.hostNetwork }}
  hostIPC: {{ .Values.apiFirewall.podSecurityPolicy.hostIPC }}
  hostPID: {{ .Values.apiFirewall.podSecurityPolicy.hostPID }}
  {{ if .Values.apiFirewall.podSecurityPolicy.runAsUser -}}
  runAsUser: {{ .Values.apiFirewall.podSecurityPolicy.runAsUser | toYaml | trimSuffix "\n" | nindent 4 }}
  {{ end -}}
  {{ if .Values.apiFirewall.podSecurityPolicy.supplementalGroups -}}
  supplementalGroups: {{ .Values.apiFirewall.podSecurityPolicy.supplementalGroups | toYaml | trimSuffix "\n" | nindent 4 }}
  {{ end -}}
  {{ if .Values.apiFirewall.podSecurityPolicy.fsGroup -}}
  fsGroup: {{ .Values.apiFirewall.podSecurityPolicy.fsGroup | toYaml | trimSuffix "\n" | nindent 4 }}
  {{ end -}}
  {{ if .Values.apiFirewall.podSecurityPolicy.seLinux -}}
  seLinux: {{ .Values.apiFirewall.podSecurityPolicy.seLinux | toYaml | trimSuffix "\n" | nindent 4 }}
  {{ end -}}
  {{ if .Values.apiFirewall.podSecurityPolicy.additionalRestrictions -}}
  {{ .Values.apiFirewall.podSecurityPolicy.additionalRestrictions | toYaml | trimSuffix "\n" | indent 2 | trimPrefix "  " }}
  {{- end }}

---
apiVersion: {{ template "role.apiVersion" . }}
kind: Role
metadata:
  name: {{ template "api-firewall.fullname" . }}-psp
  labels:
    app: {{ template "api-firewall.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: api-firewall
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - {{ template "api-firewall.fullname" . }}

---
apiVersion: {{ template "roleBinding.apiVersion" . }}
kind: RoleBinding
metadata:
  name: {{ template "api-firewall.fullname" . }}-psp
  labels:
    app: {{ template "api-firewall.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: api-firewall
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "api-firewall.fullname" . }}-psp
subjects:
- kind: ServiceAccount
  name: {{ template "api-firewall.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}

{{- end }}
