apiVersion: v1
kind: Service
metadata:
  name: {{ template "api-firewall.fullname" . }}
  labels:
    app: {{ template "api-firewall.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: api-firewall
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  {{- if .Values.apiFirewall.service.annotations }}
  annotations: {{ .Values.apiFirewall.service.annotations | toYaml | trimSuffix "\n" | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.apiFirewall.service.type }}
  {{ if .Values.apiFirewall.service.clusterIP -}}
  clusterIP: {{ .Values.apiFirewall.service.clusterIP | quote }}
  {{ end -}}
  {{ if eq .Values.apiFirewall.service.type "LoadBalancer" -}}
  {{ if .Values.apiFirewall.service.loadBalancerIP -}}
  loadBalancerIP: "{{ .Values.apiFirewall.service.loadBalancerIP }}"
  {{ end -}}
  {{ if .Values.apiFirewall.service.loadBalancerSourceRanges -}}
  loadBalancerSourceRanges: {{ toYaml .Values.apiFirewall.service.loadBalancerSourceRanges | trimSuffix "\n" | nindent 2 }}
  {{ end -}}
  {{ end -}}
  {{ if and (has .Values.apiFirewall.service.type (list "NodePort" "LoadBalancer")) (not (empty .Values.apiFirewall.service.externalTrafficPolicy)) -}}
  externalTrafficPolicy: {{ .Values.apiFirewall.service.externalTrafficPolicy }}
  {{ end -}}
  selector:
    app: {{ template "api-firewall.name" . }}
    component: api-firewall
    release: {{ .Release.Name }}
  ports:
  - name: http
    port: {{ .Values.apiFirewall.service.port }}
    targetPort: {{ .Values.apiFirewall.config.listenPort }}
    {{ if and (has .Values.apiFirewall.service.type (list "NodePort" "LoadBalancer")) (not (empty .Values.apiFirewall.service.nodePort)) -}}
    nodePort: {{ .Values.apiFirewall.service.nodePort }}
    {{ end -}}
    protocol: TCP
