{{- if not .Values.apiFirewall.serviceAccount.name -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "api-firewall.serviceAccountName" . }}
  labels:
    app: {{ template "api-firewall.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: api-firewall
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  {{ if .Values.apiFirewall.serviceAccount.annotations -}}
  annotations: {{ .Values.apiFirewall.serviceAccount.annotations | toYaml | trimSuffix "\n" | nindent 4 }}
  {{ end -}}
{{- end }}
