{{ if eq .Values.apiFirewall.target.type "endpoints" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "api-firewall.targetServiceName" . }}
  labels:
    app: {{ template "api-firewall.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: target
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  {{ if .Values.apiFirewall.target.annotations -}}
  annotations: {{ .Values.apiFirewall.target.annotations | toYaml | trimSuffix "\n" | nindent 4 }}
  {{ end -}}
spec:
  type: ClusterIP
  {{ if .Values.apiFirewall.target.clusterIP -}}
  clusterIP: {{ .Values.apiFirewall.target.clusterIP | quote }}
  {{ end -}}
  ports:
  - name: http
    port: {{ .Values.apiFirewall.target.port }}
    protocol: TCP

---
{{ if len .Values.apiFirewall.target.endpoints -}}
apiVersion: v1
kind: Endpoints
metadata:
  name: {{ template "api-firewall.targetServiceName" . }}
  labels:
    app: {{ template "api-firewall.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: target
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
subsets:
- addresses: {{ toYaml .Values.apiFirewall.target.endpoints | trimSuffix "\n" | nindent 2 }}
  ports:
  - name: http
    port: {{ .Values.apiFirewall.target.port }}
    protocol: TCP
{{ end -}}
{{ end -}}
