kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  apiServerAddress: "0.0.0.0"
  apiServerPort: 6443
  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.96.0.0/12"
nodes:
- role: control-plane
  image: kindest/node:v${KIND_NODE_VERSION}
  extraMounts:
  - hostPath: /mnt/kubernetes
    containerPath: /mnt/kubernetes
  extraPortMappings:
  - containerPort: 30080
    hostPort: 30080
    listenAddress: "0.0.0.0"
    protocol: TCP
  - containerPort: 31080
    hostPort: 31080
    listenAddress: "0.0.0.0"
    protocol: TCP
  - containerPort: 31090
    hostPort: 31090
    listenAddress: "0.0.0.0"
    protocol: TCP
  # kubeadmConfigPatches:
  # - |
  #   kind: ClusterConfiguration
  #   apiServer:
  #     extraArgs:
  #       enable-admission-plugins: PodSecurityPolicy
# - role: worker
#   image: kindest/node:v${KIND_NODE_VERSION}
#   extraMounts:
#   - hostPath: /mnt/kubernetes
#     containerPath: /mnt/kubernetes
#   kubeadmConfigPatches:
#   # - |
#   #   kind: ClusterConfiguration
#   #   apiServer:
#   #       extraArgs:
#   #         enable-admission-plugins: PodSecurityPolicy
# - role: worker
#   image: kindest/node:v${KIND_NODE_VERSION}
#   extraMounts:
#   - hostPath: /mnt/kubernetes
#     containerPath: /mnt/kubernetes
#   kubeadmConfigPatches:
#   # - |
#   #   kind: ClusterConfiguration
#   #   apiServer:
#   #       extraArgs:
#   #         enable-admission-plugins: PodSecurityPolicy
# - role: worker
#   image: kindest/node:v${KIND_NODE_VERSION}
#   extraMounts:
#   - hostPath: /mnt/kubernetes
#     containerPath: /mnt/kubernetes
#   kubeadmConfigPatches:
#   # - |
#   #   kind: ClusterConfiguration
#   #   apiServer:
#   #       extraArgs:
#   #         enable-admission-plugins: PodSecurityPolicy
