apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: httpbin
    role: backend
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: httpbin
      role: backend
  template:
    metadata:
      labels:
        app: httpbin
        role: backend
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - httpbin
                - key: role
                  operator: In
                  values:
                  - backend
              topologyKey: kubernetes.io/hostname
            weight: 100
      terminationGracePeriodSeconds: 1
      containers:
      - name: httpbin
        image: kennethreitz/httpbin
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 80
        readinessProbe:
          failureThreshold: 1
          httpGet:
            path: /get
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        livenessProbe:
          failureThreshold: 6
          httpGet:
            path: /get
            port: http
          initialDelaySeconds: 30
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
          limits:
            cpu: 350m
            memory: 250Mi

---
apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: httpbin
    role: backend
spec:
  type: NodePort
  selector:
    app: httpbin
    role: backend
  ports:
  - port: 80
    targetPort: http
    nodePort: 31090
